version: '3'

services:
  app:
    build: . #builda o dockerfile do diretorio padrao
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - redis 
      # inicia a aplicação depois que o redis tiver de pé
      
      # docker-compose exec app sh
      # npm install bull @nestjs/bull
      # npm install --save-dev @types/bull

  redis:
    image: redis:6.2.6-alpine3.14

#  "include": [
#    "src/"
#  ]
# codigo adicionado no tsconfig para ver alterações da pasta src e não do docker